### ISSUE TITLE
Typos in StringWithUint16Perfix, StringWithUint32Perfix etc.

### ISSUE THREAD

**Issue by jazz-sh** [zhuangsirui/binpacker#5]
Hello,

The following functions have typos in them.  They should end in Prefix, not Perfix

- `StringWithUint16Perfix`
- `StringWithUint32Perfix`
- `StringWithUint64Perfix`
- `BytesWithUint16Perfix`
- `BytesWithUint32Perfix`
- `BytesWithUint64Perfix`

**Comment by zhuangsirui** [comment]
so bad, it's a incompatible change :(

**Comment by jazz-sh** [comment]
I have proposed a fix.
https://github.com/zhuangsirui/binpacker/pull/6

I am happy to change the comments to a style that suits you to mark the functions as deprecated.

**Comment by zhuangsirui** [comment]
Great PR, thank you!
